// <auto-generated />
namespace RegBot.Db.MsSql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V01));
        
        string IMigrationMetadata.Id
        {
            get { return "201907192220346_V01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
