using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Common.Service.Enums
{
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CountryCode
    {
        [EnumLocalize("Россия")] 
        RU,
        [EnumLocalize("Казахстан")]
        KZ,
        [EnumLocalize("Китай")]
        CN,
        [EnumLocalize("Германия")]
        DE,
        [EnumLocalize("Великобритания")]
        EN,
        [EnumLocalize("Нидерланды")]
        NL,
        [EnumLocalize("Франция")]
        FR,
        [EnumLocalize("Украина")]
        UA,
        [EnumLocalize("Киргизия")]
        KG,
        [EnumLocalize("Узбекистан")]
        UZ,
        [EnumLocalize("Сербия")]
        RS,
        [EnumLocalize("Молдова")]
        MD,
        [EnumLocalize("Польша")]
        PL,
        [EnumLocalize("Австрия")]
        AT,
        [EnumLocalize("Латвия")]
        LV,
        [EnumLocalize("Эстония")]
        EE,
        [EnumLocalize("Египет")]
        EG,
        [EnumLocalize("Нигерия")]
        NG,
        [EnumLocalize("Гаити")]
        HT,
        [EnumLocalize("Кот-д’Ивуар")]
        CI,
        [EnumLocalize("Йемен")]
        YE,
        [EnumLocalize("Камерун")]
        CM,
        [EnumLocalize("Чад")]
        TD,
        [EnumLocalize("Швеция")]
        SE,
        [EnumLocalize("Кипр")]
        CY,
        [EnumLocalize("Испания")]
        ES,
        [EnumLocalize("США")]
        US,
        [EnumLocalize("Канада")]
        CA,
        [EnumLocalize("Индонезия")]
        ID,
        [EnumLocalize("Филиппины")]
        PH,
        [EnumLocalize("Румыния")]
        RO,
        [EnumLocalize("Чехия")]
        CZ,
        [EnumLocalize("ЮАР")]
        ZA,
        [EnumLocalize("Мьянма")]
        MM,
        [EnumLocalize("Гана")]
        GH,
        [EnumLocalize("Кения")]
        KE,
        [EnumLocalize("Грузия")]
        GE,
        [EnumLocalize("Беларусь")]
        BY,
        [EnumLocalize("Литва")]
        LT
    }
}